---
layout: cv
title: Melia Winegar's CV
---
# Melia Winegar
Data Scientist, Accountant, BYU-Idaho Student.

<div id="webaddress">
<a href="win23023@byui.edu">win23023@byui.edu</a>
| <a href="www.linkedin.com/in/melia-winegar">My LinkedIn page</a>
</div>

### Specialized In

__Soft Skills:__

- Proficient Organization Skills
- Outgoing Person
- Attention to Detail
- Critical Thinking
- Teamwork

__Hard Skills:__

- Intermediate Excel Skills
- Customer Service
- Beginning Python Programming
- Beginning Data Analysis Skills
- Public Speaking


## Education

`Graduated May 2020`
__Wasatch High School, Heber City, UT__

`Aug 2020 - May 2021,`
`Jan 2023 - May 2023`
__Utah Valley University, Orem, UT__

`Sep 2023 - Current`
__Brigham Young University - Idaho, Rexburg, ID__

__CURRENTLY PURSING: Bachelor's Degree in Accounting__


### Volunteer & Extracurricular Experience

`Jul 2021 - Dec 2022`
__Missionary__, Church of Jesus Christ of Latter Day Saints, Richmond, VA

- Worked as a Training Leader and led 20+ missionaries for three months
- Was asked to be a brand-new missionary trainer for over 10 months of my 18 month mission
- Was called into technology leadership positions for almost 6 months of my missionary experience
- Undertook being a companion, living, and consistently working with multiple disabled and struggling missionaries. Volunteer hours were 80+ hours a week

`Aug 2023 - Feb 2024`
__Logistics Supervisor__, Disciple Leadership Committe (BYU - Idaho), Rexburg, ID

- Problem solved and event planned at a proficcient  level
- Organized and planned the Disciple Leadership Conference with over 500+ attendees
- Worked with 10 others to plan and prepare to strengthen the spirituality of all attendees

` Aug 2013 - May 2020 `
__Club Member and President__, Governing Youth Council, Heber City, UT

- Was a club member for 5 years and served as the president of the Council for 1 year
- Worked with multiple students, teachers, and leaders to warn parents and students about the danger of drugs and alcohol to students.
- Gained skills in public speaking, advertisement, and public awareness

## Occupations

`Feb 2024 - Present`
__Assisstant Bookkeeper__, Winegar Real Estate Group LLC, Heber City, UT

- Developing skills in reconciling bank statements
- Pursuing proficiency in bookkeeping utilizing QuickBooks software
- Gaining expertise in invoicing processes and managing Accounts Receivable

`July 2023 - Aug 2023`
__Assembly Line Employee__, MIRO Industries, Heber City, UT

- Top worker in production lines
- Adopted and thoroughly applied Lean principles to the work environment
- Showed principles of grit and hard work as I assembled rooftop support products

`Aug 2019 - Apr 2020`
__Hostess/Busser/Food Runer Cashier__, Zermatt Hotel Restaurants, Midway, UT

- Managed to-go orders as a hostesss
- Managed and supervised the hosting station 
- Occasionally served as a food runner as well and waited tables when needed

`Jun 2018 - Aug 2018`
__Server/Barista/Cashier__, Hokulia Shaved Ice, Heber City, UT

- Maintained a clean work environment 
- Provided many forms of customer service
- Consistently and independentaly performed closing and opening duties


<!-- ### Footer

Last updated: May 2013 -->